name: integration
# This workflow is triggered on pushes to the repository. Testing!
on: [push]

jobs:
    build:
      # Job name is test-k2sc
      name: test-grad
      # This job runs on Linux
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@master

        - name: python
          uses: actions/setup-python@v1
          with:
            python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
            architecture: 'x64' # (x64 or x86)
        
        - run: pip install --upgrade jax jaxlib
          name: 'install jax'
              
        - run:
            python setup.py install
          name: 'Install morphine & dependencies'

        - run: pytest --junitxml=junit/test-results.xml 
          name: 'Run pytest'